classDiagram
    class User {
        +id
        +name
        +email
        +password
    }

    class Article {
        +id
        +title
        +content
        +userId
        +categoryId
        +tagsId
    }

    class Comment {
        +id
        +content
        +userId
        +articleId
    }

    class Tag {
        +id
        +name
    }

    class Category {
        +id
        +name
    }

   